[features]
seeds = false
skip-lint = false

[programs.devnet]
token_launch = "PSyJ5Noww1Td29VzMFDzfnEs6tVTu2uBf6UHiwUDboM"
graduation_detector = "DrA2zhr24oDrSdgK4T43HFwjQjDscfNgX5hFRvPbXWXZ"
lp_vault = "HtjSGfXNT6JSnec7gVRhjbvFZjQNVFRqbr5woGguDLq3"
harvester = "75PMkvCvvxVDxVCXZbTtDctad34Y8drbdx771xfPKtTR"
distribution = "Fop8hgm28VikzuKsMkCHzuKrspP4HerBgR5C7SPF4j6v"
shareholder_pool = "6o4VtYBwFSC59x9HBQMwUDv5fMZrLEkATPHkC7avdasW"
jackpot_pool = "C6LC5za7EurQ4Zhvf3Hz5BBgw2qayUUC4JCJTkmZY3Lc"
casino_grr_vault = "5NzSoEATixUhRYzYgJJqvEdgZnwFtQVwnvvscruS6UqN"
legal_reserve = "GGjD413tshawyi76MhrjeBFfVDzYK6vMHjbemWWBnCd1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/token-launch",
  "programs/graduation-detector",
  "programs/lp-vault",
  "programs/harvester",
  "programs/distribution",
  "programs/shareholder-pool",
  "programs/jackpot-pool",
  "programs/casino-grr-vault",
  "programs/legal-reserve"
]
